apiVersion: v1
kind: ConfigMap
metadata:
  name: besu-bootnode-config
  namespace: besu-network
  labels:
    app: besu-bootnode
    network: Besu
data:
  genesis.json: |
    {
      "config": {
        "chainId": 1947,
        "berlinBlock": 0,
        "londonBlock": 0,
        "qbft": {
          "epochlength": 30000,
          "blockperiodseconds": 2,
          "requesttimeoutseconds": 10
        }
      },
      "nonce": "0x0",
      "timestamp": "0x0",
      "gasLimit": "0x989680",
      "difficulty": "0x1",
      "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
      "coinbase": "0x0000000000000000000000000000000000000000",
      "alloc": {
        "0x0000000000000000000000000000000000000000": {
          "balance": "0x0"
        }
      },
      "extraData": "0xf83ea00000000000000000000000000000000000000000000000000000000000000000d594c0",
      "number": "0x0",
      "gasUsed": "0x0",
      "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "baseFeePerGas": "0x0"
    }
